---
name: 이현탁
surname: 
position: "학부생"
address: "서울특별시 서대문구 연희동"
phone: 010-6776-****
www: leehyeontak-blog.netlify.app/
email: "11aw1iet@naver.com"
github: "11aw1iet"
date: "`r format(Sys.time(), '%B %Y')`"
header-includes:
  - \usepackage{kotex}
output:
  vitae::hyndman:
    pdf_document:
      latex_engine: xelatex
mainfont: NanumBarunpen      
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# 학교

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "문과", "2011~2013", "하남고등학교", "대한민국, 경기도",
   "문과", "2014", "송파스카이에듀", "대한민국, 서울",
  "응용통계학과", "2015~", "연세대학교", "대한민국, 서울",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# 경력

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  "2011 ~ 2012", "환경정화활동", "하남고 수피아 회원",
  "2015 ~ 현재", "응용통계학과 전공", "연세대",
  "2015 ~ 2015", "밴드 활동", "응용통계학과 밴드 스밴",
  "2016 ~ 2018", "대한민국 육군", "포병대 견인포 운전병",
  "2018 ~ 2018", "맛집탐방", "맛집탐방 동아리 미어캣",
  "2019 ~ 2019", "보드게임", "보드게임 동아리 홍보동",
  "2020 ~ 2020", "독서모임", "독서토론 소모임 책책짹짹 창설 및 운영"
  ) %>% 
  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Desc
  )
```

# 이수과목

```{r}
tribble(
  ~Year, ~Type, ~Teacher,
  "2015", "통계학입문", "김철응",
  "2015", "미분적분학", "이호규",
  "2015","선형대수", "이호규",
  "2016", "컴퓨터 자료처리", "한선우",
  "2018", "금융리스크 실무와 통계학", "김상철",
  "2018", "통계방법론", "김아현",
  "2018", "수리통계학(1)", "박태영",
  "2019", "표본추출이론", "강상욱",
  "2019", "회귀분석", "김현태",
  "2019", "확률과정", "박태영",) %>%  brief_entries(
    glue::glue("{Type}"),
    Year, 
    Teacher
  )    
```